/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_LED_BLINK_PB_H_INCLUDED
#define PB_LED_BLINK_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _LedStatus {
    int32_t status;
} LedStatus;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define LedStatus_init_default                   {0}
#define LedStatus_init_zero                      {0}

/* Field tags (for use in manual encoding/decoding) */
#define LedStatus_status_tag                     1

/* Struct field encoding specification for nanopb */
#define LedStatus_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, INT32,    status,            1)
#define LedStatus_CALLBACK NULL
#define LedStatus_DEFAULT NULL

extern const pb_msgdesc_t LedStatus_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define LedStatus_fields &LedStatus_msg

/* Maximum encoded size of messages (where known) */
#define LED_BLINK_PB_H_MAX_SIZE                  LedStatus_size
#define LedStatus_size                           11

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
